### ISSUE TITLE
MW - data without any meaning - only lexical information

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/csl-orig#1060]
```
<L>1308<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3
<s>agriya—vat</s> ¦ <lex>mfn.</lex><info lex="m:f:n"/>
<LEND>
<L>1309<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3B
<s>agriya—vat</s> ¦ <lex>f.</lex> <s>vatI</s> (<ab>scil.</ab> <s>fc</s>), <ab>N.</ab> of the hymn <s1 slp1="fg">Ṛg</s1>-<s1 slp1="veda">veda</s1> <ls n="RV.">ix, 62, 25</ls>, quoted in <ls>Lāṭy.</ls><info lex="f"/>
<LEND>
```
Is it usual for such information to be there? or was it supposed to be merged with the second entry, @funderburkjim ?

**Comment by Andhrabharati** [comment]
There are few thousands of such entries (without the meaning--or, body-- portion) in the mw.txt,  and I have merged those appropriately with other entries or deleted altogether, as many of them are brought out separately with some kind of `<lex type="xxx">` tagging.

**Comment by drdhaval2785** [comment]
OK.

**Comment by funderburkjim** [comment]
Here is current mw_AB version of agriyavat
```
<s>agriya—vat</s>, <lex>mfn.</lex>; <lex>f.</lex> <s>{vatī}</s> (<ab>scil.</ab> 
<s>ṛc</s>),	¦ <ab>N.</ab> of the hymn <s1>Ṛg-veda</s1> <ls n="RV.">ix, 62, 25</ls>, 
quoted in <ls>Lāṭy.</ls>
```
Seems a good solution.

![image](https://user-images.githubusercontent.com/6393033/218537105-9223fcd8-2ced-4f8c-9328-4c9cbcf12020.png)

**Comment by gasyoun** [comment]
<details>
<summary>🤖 Agent research findings</summary>

**Question type:** editorial-policy

**Evidence found:**

The example entry from the issue body (`<L>1308` `agriya—vat`, `<lex>mfn.</lex>` with no body text) is confirmed still present in current `mw.txt` at line 4778:
```
<L>1308<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3
<s>agriya—vat</s> ¦ <lex>mfn.</lex><info lex="m:f:n"/>
<LEND>
```
The following entry L>1309 (line 4780–4782) carries the actual content (N. of the hymn RV ix, 62, 25). The funderburkjim `mw_AB` merged solution shown in comment #1428415438 has **not yet been applied** to `mw.txt`.

Andhrabharati noted (comment #1427384225): "There are few thousands of such entries ... I have merged many of those (more remaining still)." This confirms the `agriyavat` L>1308 case is one of many not yet resolved.

**Assessment:**

Partially answerable: the editorial policy (merge body-less entries with their continuation) is settled per the comments. The specific `agriyavat` L>1308 example remains unmerged in the current file.

**Suggested next step:** Apply the agreed merge for L>1308/L>1309 in `mw.txt`: combine both entries so the `mfn.` lex tag and the `f. vatī (scil. ṛc)` content appear in a single entry, following the `mw_AB` pattern shown by funderburkjim.

</details>

**Comment by gasyoun** [comment]
<details>
<summary>🤖 Bug triage findings</summary>

**Bug class:** source-error (body-less stub entry not yet merged with continuation entry)

**Evidence:**

Current `mw.txt` lines 4777–4782 (confirmed in local clone):
```
<L>1308<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3
<s>agriya—vat</s> ¦ <lex>mfn.</lex><info lex="m:f:n"/>
<LEND>
<L>1309<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3B
<s>agriya—vat</s> ¦ <lex>f.</lex> <s>vatI</s> (<ab>scil.</ab> <s>fc</s>), <ab>N.</ab> of the hymn <s1>Ṛg</s1>-<s1>veda</s1> <ls n="RV.">ix, 62, 25</ls>, quoted in <ls>Lāṭy.</ls><info lex="f"/>
<LEND>
```

L>1308 contains only a `<lex>mfn.</lex>` tag with no body/definition — a stub. L>1309 holds the actual content. The merge shown by @funderburkjim in comment [#1428415438](https://github.com/sanskrit-lexicon/csl-orig/issues/1060#issuecomment-1428415438) has **not been applied** to the current file.

The editorial policy (merge body-less entries with their continuation) is already settled per the 2023 discussion.

**Agent-fixable (Tier A)?** Yes

**Proposed fix:**

Replace both entries (lines 4777–4782) with a single merged entry. Based on the `mw_AB` pattern shown by @funderburkjim:

```
<L>1308<pc>6,3<k1>agriyavat<k2>agriya—vat<e>3
<s>agriya—vat</s> ¦ <lex>mfn.</lex> <lex>f.</lex> <s>vatI</s> (<ab>scil.</ab> <s>fc</s>), <ab>N.</ab> of the hymn <s1>Ṛg</s1>-<s1>veda</s1> <ls n="RV.">ix, 62, 25</ls>, quoted in <ls>Lāṭy.</ls><info lex="m:f:n" lex2="f"/>
<LEND>
```

(with L>1309 deleted). Exact `<info>` tag format and L-number assignment to follow whatever convention Andhrabharati is already using for the other thousands of similar merges.

**Suggested next step:** Assign to @Andhrabharati's ongoing batch of body-less entry merges, or apply the specific L>1308/L>1309 merge via `updateByLine.py` change file + XML validation before committing.

</details>

**Comment by gasyoun** [comment]
PR opened: https://github.com/sanskrit-lexicon/csl-orig/pull/2869
